/* Note:  This file was autogenerated by Database/JsonToIPC.py */
/*        See Database/Readme.txt for details. */
/*        If you are hand-modifying this file, keep in mind that */
/*        your work will be lost if you run JsonToIPC.py again. */

#include "Ac.h"

/**********************************************************************/
void WriteToSocket(SOCKET Socket, struct AcType *AC)
{

   long Isc, Iorb, Iw, Ipfx, i;
   char AckMsg[5] = "Ack\n";
   char Msg[16384];
   long MsgLen = 0;
   long LineLen;
   long PfxLen;
   char line[512];

   Isc = AC->ID;

   sprintf(line, "SC[%ld].AC.svb = %18.12le %18.12le %18.12le\n", Isc,
           AC->svb.v[0], AC->svb.v[1], AC->svb.v[2]);
   LineLen = strlen(line);
   memcpy(&Msg[MsgLen], line, LineLen);
   MsgLen += LineLen;
   if (AC->EchoEnabled)
      printf("%s", line);

   sprintf(line, "SC[%ld].AC.bvb = %18.12le %18.12le %18.12le\n", Isc,
           AC->bvb.v[0], AC->bvb.v[1], AC->bvb.v[2]);
   LineLen = strlen(line);
   memcpy(&Msg[MsgLen], line, LineLen);
   MsgLen += LineLen;
   if (AC->EchoEnabled)
      printf("%s", line);

   sprintf(line, "SC[%ld].AC.Hvb = %18.12le %18.12le %18.12le\n", Isc,
           AC->Hvb.v[0], AC->Hvb.v[1], AC->Hvb.v[2]);
   LineLen = strlen(line);
   memcpy(&Msg[MsgLen], line, LineLen);
   MsgLen += LineLen;
   if (AC->EchoEnabled)
      printf("%s", line);

   for (i = 0; i < AC->Ng; i++) {
      sprintf(line,
              "SC[%ld].AC.G[%ld].Cmd.AngRate = %18.12le %18.12le %18.12le\n",
              Isc, i, AC->G[i].Cmd.AngRate.v[0], AC->G[i].Cmd.AngRate.v[1],
              AC->G[i].Cmd.AngRate.v[2]);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.G[%ld].Cmd.Ang = %18.12le %18.12le %18.12le\n",
              Isc, i, AC->G[i].Cmd.Ang.v[0], AC->G[i].Cmd.Ang.v[1],
              AC->G[i].Cmd.Ang.v[2]);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);
   }

   for (i = 0; i < AC->Nwhl; i++) {
      sprintf(line, "SC[%ld].AC.Whl[%ld].Tcmd = %18.12le\n", Isc, i,
              AC->Whl[i].Tcmd);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);
   }

   for (i = 0; i < AC->Nmtb; i++) {
      sprintf(line, "SC[%ld].AC.MTB[%ld].Mcmd = %18.12le\n", Isc, i,
              AC->MTB[i].Mcmd);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);
   }

   for (i = 0; i < AC->Nthr; i++) {
      sprintf(line, "SC[%ld].AC.Thr[%ld].PulseWidthCmd = %18.12le\n", Isc, i,
              AC->Thr[i].PulseWidthCmd);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.Thr[%ld].ThrustLevelCmd = %18.12le\n", Isc, i,
              AC->Thr[i].ThrustLevelCmd);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);
   }

   sprintf(line, "SC[%ld].AC.Cmd.AngRate = %18.12le %18.12le %18.12le\n", Isc,
           AC->Cmd.AngRate.v[0], AC->Cmd.AngRate.v[1], AC->Cmd.AngRate.v[2]);
   LineLen = strlen(line);
   memcpy(&Msg[MsgLen], line, LineLen);
   MsgLen += LineLen;
   if (AC->EchoEnabled)
      printf("%s", line);

   sprintf(line, "SC[%ld].AC.Cmd.Ang = %18.12le %18.12le %18.12le\n", Isc,
           AC->Cmd.Ang.v[0], AC->Cmd.Ang.v[1], AC->Cmd.Ang.v[2]);
   LineLen = strlen(line);
   memcpy(&Msg[MsgLen], line, LineLen);
   MsgLen += LineLen;
   if (AC->EchoEnabled)
      printf("%s", line);

   if (AC->ParmDumpEnabled) {
      sprintf(line, "SC[%ld].AC.ID = %ld\n", Isc, AC->ID);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.EchoEnabled = %ld\n", Isc, AC->EchoEnabled);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.Nb = %ld\n", Isc, AC->Nb);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.Ng = %ld\n", Isc, AC->Ng);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.Nwhl = %ld\n", Isc, AC->Nwhl);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.Nmtb = %ld\n", Isc, AC->Nmtb);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.Nthr = %ld\n", Isc, AC->Nthr);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.Ncmg = %ld\n", Isc, AC->Ncmg);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.Ngyro = %ld\n", Isc, AC->Ngyro);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.Nmag = %ld\n", Isc, AC->Nmag);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.Ncss = %ld\n", Isc, AC->Ncss);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.Nfss = %ld\n", Isc, AC->Nfss);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.Nst = %ld\n", Isc, AC->Nst);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.Ngps = %ld\n", Isc, AC->Ngps);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.Nacc = %ld\n", Isc, AC->Nacc);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.Pi = %18.12le\n", Isc, AC->Pi);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.TwoPi = %18.12le\n", Isc, AC->TwoPi);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.DT = %18.12le\n", Isc, AC->DT);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.mass = %18.12le\n", Isc, AC->mass);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.cm = %18.12le %18.12le %18.12le\n", Isc,
              AC->cm.v[0], AC->cm.v[1], AC->cm.v[2]);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line,
              "SC[%ld].AC.MOI = %18.12le %18.12le %18.12le %18.12le %18.12le "
              "%18.12le %18.12le %18.12le %18.12le\n",
              Isc, AC->MOI.mat[0][0], AC->MOI.mat[0][1], AC->MOI.mat[0][2],
              AC->MOI.mat[1][0], AC->MOI.mat[1][1], AC->MOI.mat[1][2],
              AC->MOI.mat[2][0], AC->MOI.mat[2][1], AC->MOI.mat[2][2]);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      for (i = 0; i < AC->Nb; i++) {
         sprintf(line, "SC[%ld].AC.B[%ld].mass = %18.12le\n", Isc, i,
                 AC->B[i].mass);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);

         sprintf(line, "SC[%ld].AC.B[%ld].cm = %18.12le %18.12le %18.12le\n",
                 Isc, i, AC->B[i].cm.v[0], AC->B[i].cm.v[1], AC->B[i].cm.v[2]);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);

         sprintf(line,
                 "SC[%ld].AC.B[%ld].MOI = %18.12le %18.12le %18.12le %18.12le "
                 "%18.12le %18.12le %18.12le %18.12le %18.12le\n",
                 Isc, i, AC->B[i].MOI.mat[0][0], AC->B[i].MOI.mat[0][1],
                 AC->B[i].MOI.mat[0][2], AC->B[i].MOI.mat[1][0],
                 AC->B[i].MOI.mat[1][1], AC->B[i].MOI.mat[1][2],
                 AC->B[i].MOI.mat[2][0], AC->B[i].MOI.mat[2][1],
                 AC->B[i].MOI.mat[2][2]);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);
      }

      for (i = 0; i < AC->Ng; i++) {
         sprintf(line, "SC[%ld].AC.G[%ld].IsSpherical = %ld\n", Isc, i,
                 AC->G[i].IsSpherical);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);

         sprintf(line, "SC[%ld].AC.G[%ld].RotDOF = %ld\n", Isc, i,
                 AC->G[i].RotDOF);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);

         sprintf(line, "SC[%ld].AC.G[%ld].TrnDOF = %ld\n", Isc, i,
                 AC->G[i].TrnDOF);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);

         sprintf(line, "SC[%ld].AC.G[%ld].RotSeq = %ld\n", Isc, i,
                 AC->G[i].RotSeq);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);

         sprintf(line, "SC[%ld].AC.G[%ld].TrnSeq = %ld\n", Isc, i,
                 AC->G[i].TrnSeq);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);

         sprintf(line,
                 "SC[%ld].AC.G[%ld].CGiBi = %18.12le %18.12le %18.12le "
                 "%18.12le %18.12le %18.12le %18.12le %18.12le %18.12le\n",
                 Isc, i, AC->G[i].CGiBi.mat[0][0], AC->G[i].CGiBi.mat[0][1],
                 AC->G[i].CGiBi.mat[0][2], AC->G[i].CGiBi.mat[1][0],
                 AC->G[i].CGiBi.mat[1][1], AC->G[i].CGiBi.mat[1][2],
                 AC->G[i].CGiBi.mat[2][0], AC->G[i].CGiBi.mat[2][1],
                 AC->G[i].CGiBi.mat[2][2]);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);

         sprintf(line,
                 "SC[%ld].AC.G[%ld].CBoGo = %18.12le %18.12le %18.12le "
                 "%18.12le %18.12le %18.12le %18.12le %18.12le %18.12le\n",
                 Isc, i, AC->G[i].CBoGo.mat[0][0], AC->G[i].CBoGo.mat[0][1],
                 AC->G[i].CBoGo.mat[0][2], AC->G[i].CBoGo.mat[1][0],
                 AC->G[i].CBoGo.mat[1][1], AC->G[i].CBoGo.mat[1][2],
                 AC->G[i].CBoGo.mat[2][0], AC->G[i].CBoGo.mat[2][1],
                 AC->G[i].CBoGo.mat[2][2]);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);

         sprintf(line,
                 "SC[%ld].AC.G[%ld].AngGain = %18.12le %18.12le %18.12le\n",
                 Isc, i, AC->G[i].AngGain.v[0], AC->G[i].AngGain.v[1],
                 AC->G[i].AngGain.v[2]);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);

         sprintf(line,
                 "SC[%ld].AC.G[%ld].AngRateGain = %18.12le %18.12le %18.12le\n",
                 Isc, i, AC->G[i].AngRateGain.v[0], AC->G[i].AngRateGain.v[1],
                 AC->G[i].AngRateGain.v[2]);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);

         sprintf(line,
                 "SC[%ld].AC.G[%ld].PosGain = %18.12le %18.12le %18.12le\n",
                 Isc, i, AC->G[i].PosGain.v[0], AC->G[i].PosGain.v[1],
                 AC->G[i].PosGain.v[2]);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);

         sprintf(line,
                 "SC[%ld].AC.G[%ld].PosRateGain = %18.12le %18.12le %18.12le\n",
                 Isc, i, AC->G[i].PosRateGain.v[0], AC->G[i].PosRateGain.v[1],
                 AC->G[i].PosRateGain.v[2]);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);

         sprintf(line,
                 "SC[%ld].AC.G[%ld].MaxAngRate = %18.12le %18.12le %18.12le\n",
                 Isc, i, AC->G[i].MaxAngRate.v[0], AC->G[i].MaxAngRate.v[1],
                 AC->G[i].MaxAngRate.v[2]);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);

         sprintf(line,
                 "SC[%ld].AC.G[%ld].MaxPosRate = %18.12le %18.12le %18.12le\n",
                 Isc, i, AC->G[i].MaxPosRate.v[0], AC->G[i].MaxPosRate.v[1],
                 AC->G[i].MaxPosRate.v[2]);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);

         sprintf(line,
                 "SC[%ld].AC.G[%ld].MaxTrq = %18.12le %18.12le %18.12le\n", Isc,
                 i, AC->G[i].MaxTrq.v[0], AC->G[i].MaxTrq.v[1],
                 AC->G[i].MaxTrq.v[2]);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);

         sprintf(line,
                 "SC[%ld].AC.G[%ld].MaxFrc = %18.12le %18.12le %18.12le\n", Isc,
                 i, AC->G[i].MaxFrc.v[0], AC->G[i].MaxFrc.v[1],
                 AC->G[i].MaxFrc.v[2]);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);
      }

      for (i = 0; i < AC->Ngyro; i++) {
         sprintf(line,
                 "SC[%ld].AC.Gyro[%ld].Axis = %18.12le %18.12le %18.12le\n",
                 Isc, i, AC->Gyro[i].Axis.v[0], AC->Gyro[i].Axis.v[1],
                 AC->Gyro[i].Axis.v[2]);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);
      }

      for (i = 0; i < AC->Nmag; i++) {
         sprintf(line,
                 "SC[%ld].AC.MAG[%ld].Axis = %18.12le %18.12le %18.12le\n", Isc,
                 i, AC->MAG[i].Axis.v[0], AC->MAG[i].Axis.v[1],
                 AC->MAG[i].Axis.v[2]);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);
      }

      for (i = 0; i < AC->Ncss; i++) {
         sprintf(line, "SC[%ld].AC.CSS[%ld].Body = %ld\n", Isc, i,
                 AC->CSS[i].Body);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);

         sprintf(line,
                 "SC[%ld].AC.CSS[%ld].Axis = %18.12le %18.12le %18.12le\n", Isc,
                 i, AC->CSS[i].Axis.v[0], AC->CSS[i].Axis.v[1],
                 AC->CSS[i].Axis.v[2]);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);

         sprintf(line, "SC[%ld].AC.CSS[%ld].Scale = %18.12le\n", Isc, i,
                 AC->CSS[i].Scale);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);
      }

      for (i = 0; i < AC->Nfss; i++) {
         sprintf(
             line,
             "SC[%ld].AC.FSS[%ld].qb = %18.12le %18.12le %18.12le %18.12le\n",
             Isc, i, AC->FSS[i].qb.q[0], AC->FSS[i].qb.q[1], AC->FSS[i].qb.q[2],
             AC->FSS[i].qb.q[3]);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);

         sprintf(line,
                 "SC[%ld].AC.FSS[%ld].CB = %18.12le %18.12le %18.12le %18.12le "
                 "%18.12le %18.12le %18.12le %18.12le %18.12le\n",
                 Isc, i, AC->FSS[i].CB.mat[0][0], AC->FSS[i].CB.mat[0][1],
                 AC->FSS[i].CB.mat[0][2], AC->FSS[i].CB.mat[1][0],
                 AC->FSS[i].CB.mat[1][1], AC->FSS[i].CB.mat[1][2],
                 AC->FSS[i].CB.mat[2][0], AC->FSS[i].CB.mat[2][1],
                 AC->FSS[i].CB.mat[2][2]);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);
      }

      for (i = 0; i < AC->Nst; i++) {
         sprintf(
             line,
             "SC[%ld].AC.ST[%ld].qb = %18.12le %18.12le %18.12le %18.12le\n",
             Isc, i, AC->ST[i].qb.q[0], AC->ST[i].qb.q[1], AC->ST[i].qb.q[2],
             AC->ST[i].qb.q[3]);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);

         sprintf(line,
                 "SC[%ld].AC.ST[%ld].CB = %18.12le %18.12le %18.12le %18.12le "
                 "%18.12le %18.12le %18.12le %18.12le %18.12le\n",
                 Isc, i, AC->ST[i].CB.mat[0][0], AC->ST[i].CB.mat[0][1],
                 AC->ST[i].CB.mat[0][2], AC->ST[i].CB.mat[1][0],
                 AC->ST[i].CB.mat[1][1], AC->ST[i].CB.mat[1][2],
                 AC->ST[i].CB.mat[2][0], AC->ST[i].CB.mat[2][1],
                 AC->ST[i].CB.mat[2][2]);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);
      }

      for (i = 0; i < AC->Nacc; i++) {
         sprintf(line,
                 "SC[%ld].AC.Accel[%ld].PosB = %18.12le %18.12le %18.12le\n",
                 Isc, i, AC->Accel[i].PosB.v[0], AC->Accel[i].PosB.v[1],
                 AC->Accel[i].PosB.v[2]);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);

         sprintf(line,
                 "SC[%ld].AC.Accel[%ld].Axis = %18.12le %18.12le %18.12le\n",
                 Isc, i, AC->Accel[i].Axis.v[0], AC->Accel[i].Axis.v[1],
                 AC->Accel[i].Axis.v[2]);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);
      }

      for (i = 0; i < AC->Nwhl; i++) {
         sprintf(line, "SC[%ld].AC.Whl[%ld].Body = %ld\n", Isc, i,
                 AC->Whl[i].Body);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);

         sprintf(line,
                 "SC[%ld].AC.Whl[%ld].Axis = %18.12le %18.12le %18.12le\n", Isc,
                 i, AC->Whl[i].Axis.v[0], AC->Whl[i].Axis.v[1],
                 AC->Whl[i].Axis.v[2]);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);

         sprintf(line,
                 "SC[%ld].AC.Whl[%ld].DistVec = %18.12le %18.12le %18.12le\n",
                 Isc, i, AC->Whl[i].DistVec.v[0], AC->Whl[i].DistVec.v[1],
                 AC->Whl[i].DistVec.v[2]);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);

         sprintf(line, "SC[%ld].AC.Whl[%ld].J = %18.12le\n", Isc, i,
                 AC->Whl[i].J);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);

         sprintf(line, "SC[%ld].AC.Whl[%ld].Tmax = %18.12le\n", Isc, i,
                 AC->Whl[i].Tmax);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);

         sprintf(line, "SC[%ld].AC.Whl[%ld].Hmax = %18.12le\n", Isc, i,
                 AC->Whl[i].Hmax);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);
      }

      for (i = 0; i < AC->Nmtb; i++) {
         sprintf(line,
                 "SC[%ld].AC.MTB[%ld].Axis = %18.12le %18.12le %18.12le\n", Isc,
                 i, AC->MTB[i].Axis.v[0], AC->MTB[i].Axis.v[1],
                 AC->MTB[i].Axis.v[2]);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);

         sprintf(line,
                 "SC[%ld].AC.MTB[%ld].DistVec = %18.12le %18.12le %18.12le\n",
                 Isc, i, AC->MTB[i].DistVec.v[0], AC->MTB[i].DistVec.v[1],
                 AC->MTB[i].DistVec.v[2]);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);

         sprintf(line, "SC[%ld].AC.MTB[%ld].Mmax = %18.12le\n", Isc, i,
                 AC->MTB[i].Mmax);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);
      }

      for (i = 0; i < AC->Nthr; i++) {
         sprintf(line, "SC[%ld].AC.Thr[%ld].Body = %ld\n", Isc, i,
                 AC->Thr[i].Body);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);

         sprintf(line,
                 "SC[%ld].AC.Thr[%ld].PosB = %18.12le %18.12le %18.12le\n", Isc,
                 i, AC->Thr[i].PosB.v[0], AC->Thr[i].PosB.v[1],
                 AC->Thr[i].PosB.v[2]);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);

         sprintf(line,
                 "SC[%ld].AC.Thr[%ld].Axis = %18.12le %18.12le %18.12le\n", Isc,
                 i, AC->Thr[i].Axis.v[0], AC->Thr[i].Axis.v[1],
                 AC->Thr[i].Axis.v[2]);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);

         sprintf(line, "SC[%ld].AC.Thr[%ld].rxA = %18.12le %18.12le %18.12le\n",
                 Isc, i, AC->Thr[i].rxA.v[0], AC->Thr[i].rxA.v[1],
                 AC->Thr[i].rxA.v[2]);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);

         sprintf(line, "SC[%ld].AC.Thr[%ld].Fmax = %18.12le\n", Isc, i,
                 AC->Thr[i].Fmax);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen], line, LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled)
            printf("%s", line);
      }

      sprintf(line, "SC[%ld].AC.PrototypeCtrl.wc = %18.12le\n", Isc,
              AC->PrototypeCtrl.wc);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.PrototypeCtrl.amax = %18.12le\n", Isc,
              AC->PrototypeCtrl.amax);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.PrototypeCtrl.vmax = %18.12le\n", Isc,
              AC->PrototypeCtrl.vmax);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.PrototypeCtrl.Kprec = %18.12le\n", Isc,
              AC->PrototypeCtrl.Kprec);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.PrototypeCtrl.Knute = %18.12le\n", Isc,
              AC->PrototypeCtrl.Knute);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.AdHocCtrl.Kr = %18.12le %18.12le %18.12le\n",
              Isc, AC->AdHocCtrl.Kr.v[0], AC->AdHocCtrl.Kr.v[1],
              AC->AdHocCtrl.Kr.v[2]);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.AdHocCtrl.Kp = %18.12le %18.12le %18.12le\n",
              Isc, AC->AdHocCtrl.Kp.v[0], AC->AdHocCtrl.Kp.v[1],
              AC->AdHocCtrl.Kp.v[2]);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.SpinnerCtrl.Ispin = %18.12le\n", Isc,
              AC->SpinnerCtrl.Ispin);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.SpinnerCtrl.Itrans = %18.12le\n", Isc,
              AC->SpinnerCtrl.Itrans);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.SpinnerCtrl.SpinRate = %18.12le\n", Isc,
              AC->SpinnerCtrl.SpinRate);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.SpinnerCtrl.Knute = %18.12le\n", Isc,
              AC->SpinnerCtrl.Knute);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.SpinnerCtrl.Kprec = %18.12le\n", Isc,
              AC->SpinnerCtrl.Kprec);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line,
              "SC[%ld].AC.ThreeAxisCtrl.Kr = %18.12le %18.12le %18.12le\n", Isc,
              AC->ThreeAxisCtrl.Kr.v[0], AC->ThreeAxisCtrl.Kr.v[1],
              AC->ThreeAxisCtrl.Kr.v[2]);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line,
              "SC[%ld].AC.ThreeAxisCtrl.Kp = %18.12le %18.12le %18.12le\n", Isc,
              AC->ThreeAxisCtrl.Kp.v[0], AC->ThreeAxisCtrl.Kp.v[1],
              AC->ThreeAxisCtrl.Kp.v[2]);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.ThreeAxisCtrl.Kunl = %18.12le\n", Isc,
              AC->ThreeAxisCtrl.Kunl);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.IssCtrl.Kr = %18.12le %18.12le %18.12le\n", Isc,
              AC->IssCtrl.Kr.v[0], AC->IssCtrl.Kr.v[1], AC->IssCtrl.Kr.v[2]);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.IssCtrl.Kp = %18.12le %18.12le %18.12le\n", Isc,
              AC->IssCtrl.Kp.v[0], AC->IssCtrl.Kp.v[1], AC->IssCtrl.Kp.v[2]);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.IssCtrl.Tmax = %18.12le\n", Isc,
              AC->IssCtrl.Tmax);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.CmgCtrl.Kr = %18.12le %18.12le %18.12le\n", Isc,
              AC->CmgCtrl.Kr.v[0], AC->CmgCtrl.Kr.v[1], AC->CmgCtrl.Kr.v[2]);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.CmgCtrl.Kp = %18.12le %18.12le %18.12le\n", Isc,
              AC->CmgCtrl.Kp.v[0], AC->CmgCtrl.Kp.v[1], AC->CmgCtrl.Kp.v[2]);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.ThrCtrl.Kw = %18.12le %18.12le %18.12le\n", Isc,
              AC->ThrCtrl.Kw.v[0], AC->ThrCtrl.Kw.v[1], AC->ThrCtrl.Kw.v[2]);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.ThrCtrl.Kth = %18.12le %18.12le %18.12le\n",
              Isc, AC->ThrCtrl.Kth.v[0], AC->ThrCtrl.Kth.v[1],
              AC->ThrCtrl.Kth.v[2]);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.ThrCtrl.Kv = %18.12le\n", Isc, AC->ThrCtrl.Kv);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.ThrCtrl.Kp = %18.12le\n", Isc, AC->ThrCtrl.Kp);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.CfsCtrl.Kr = %18.12le %18.12le %18.12le\n", Isc,
              AC->CfsCtrl.Kr.v[0], AC->CfsCtrl.Kr.v[1], AC->CfsCtrl.Kr.v[2]);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.CfsCtrl.Kp = %18.12le %18.12le %18.12le\n", Isc,
              AC->CfsCtrl.Kp.v[0], AC->CfsCtrl.Kp.v[1], AC->CfsCtrl.Kp.v[2]);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.CfsCtrl.Kunl = %18.12le\n", Isc,
              AC->CfsCtrl.Kunl);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.ThrSteerCtrl.Kr = %18.12le %18.12le %18.12le\n",
              Isc, AC->ThrSteerCtrl.Kr.v[0], AC->ThrSteerCtrl.Kr.v[1],
              AC->ThrSteerCtrl.Kr.v[2]);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);

      sprintf(line, "SC[%ld].AC.ThrSteerCtrl.Kp = %18.12le %18.12le %18.12le\n",
              Isc, AC->ThrSteerCtrl.Kp.v[0], AC->ThrSteerCtrl.Kp.v[1],
              AC->ThrSteerCtrl.Kp.v[2]);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen], line, LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled)
         printf("%s", line);
   }

   sprintf(line, "[EOF]\n\n");
   if (AC->EchoEnabled)
      printf("%s", line);

   LineLen = strlen(line);
   memcpy(&Msg[MsgLen], line, LineLen);
   MsgLen += LineLen;
   send(Socket, Msg, MsgLen, 0);

   /* Wait for Ack */
   recv(Socket, AckMsg, 5, 0);
}
