/* Note:  This file was autogenerated by Database/JsonToIPC.py */
/*        See Database/Readme.txt for details. */
/*        If you are hand-modifying this file, keep in mind that */
/*        your work will be lost if you run JsonToIPC.py again. */

#include "42.h"

/**********************************************************************/
void WriteToFile(FILE *StateFile, char **Prefix, long Nprefix, long EchoEnabled)
{

   long Isc, Iorb, Iw, Ipfx, i;
   long PfxLen;
   char line[512];

   sprintf(line, "TIME %ld-%03ld-%02ld:%02ld:%012.9lf\n", UTC.Year, UTC.doy,
           UTC.Hour, UTC.Minute, rational2double(UTC.Second));
   fprintf(StateFile, "%s", line);
   if (EchoEnabled)
      printf("%s", line);

   for (Ipfx = 0; Ipfx < Nprefix; Ipfx++) {
      PfxLen = strlen(Prefix[Ipfx]);

      for (Isc = 0; Isc < Nsc; Isc++) {
         if (SC[Isc].Exists) {
            sprintf(line, "SC[%ld].PosR = %18.12le %18.12le %18.12le\n", Isc,
                    SC[Isc].PosR.v[0], SC[Isc].PosR.v[1], SC[Isc].PosR.v[2]);
            if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
               fprintf(StateFile, "%s", line);
               if (EchoEnabled)
                  printf("%s", line);
            }

            sprintf(line, "SC[%ld].VelR = %18.12le %18.12le %18.12le\n", Isc,
                    SC[Isc].VelR.v[0], SC[Isc].VelR.v[1], SC[Isc].VelR.v[2]);
            if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
               fprintf(StateFile, "%s", line);
               if (EchoEnabled)
                  printf("%s", line);
            }

            sprintf(line, "SC[%ld].svb = %18.12le %18.12le %18.12le\n", Isc,
                    SC[Isc].svb.v[0], SC[Isc].svb.v[1], SC[Isc].svb.v[2]);
            if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
               fprintf(StateFile, "%s", line);
               if (EchoEnabled)
                  printf("%s", line);
            }

            sprintf(line, "SC[%ld].bvb = %18.12le %18.12le %18.12le\n", Isc,
                    SC[Isc].bvb.v[0], SC[Isc].bvb.v[1], SC[Isc].bvb.v[2]);
            if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
               fprintf(StateFile, "%s", line);
               if (EchoEnabled)
                  printf("%s", line);
            }

            sprintf(line, "SC[%ld].Hvb = %18.12le %18.12le %18.12le\n", Isc,
                    SC[Isc].Hvb.v[0], SC[Isc].Hvb.v[1], SC[Isc].Hvb.v[2]);
            if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
               fprintf(StateFile, "%s", line);
               if (EchoEnabled)
                  printf("%s", line);
            }

            sprintf(line, "SC[%ld].AC.ParmLoadEnabled = %ld\n", Isc,
                    SC[Isc].AC.ParmLoadEnabled);
            if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
               fprintf(StateFile, "%s", line);
               if (EchoEnabled)
                  printf("%s", line);
            }

            sprintf(line, "SC[%ld].AC.ParmDumpEnabled = %ld\n", Isc,
                    SC[Isc].AC.ParmDumpEnabled);
            if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
               fprintf(StateFile, "%s", line);
               if (EchoEnabled)
                  printf("%s", line);
            }

            for (i = 0; i < SC[Isc].AC.Ng; i++) {
               sprintf(line,
                       "SC[%ld].AC.G[%ld].Ang = %18.12le %18.12le %18.12le\n",
                       Isc, i, SC[Isc].AC.G[i].Ang.v[0],
                       SC[Isc].AC.G[i].Ang.v[1], SC[Isc].AC.G[i].Ang.v[2]);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }
            }

            for (i = 0; i < SC[Isc].AC.Ngyro; i++) {
               sprintf(line, "SC[%ld].AC.Gyro[%ld].Rate = %18.12le\n", Isc, i,
                       SC[Isc].AC.Gyro[i].Rate);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }
            }

            for (i = 0; i < SC[Isc].AC.Nmag; i++) {
               sprintf(line, "SC[%ld].AC.MAG[%ld].Field = %18.12le\n", Isc, i,
                       SC[Isc].AC.MAG[i].Field);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }
            }

            for (i = 0; i < SC[Isc].AC.Ncss; i++) {
               sprintf(line, "SC[%ld].AC.CSS[%ld].Valid = %ld\n", Isc, i,
                       SC[Isc].AC.CSS[i].Valid);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.CSS[%ld].Illum = %18.12le\n", Isc, i,
                       SC[Isc].AC.CSS[i].Illum);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }
            }

            for (i = 0; i < SC[Isc].AC.Nfss; i++) {
               sprintf(line, "SC[%ld].AC.FSS[%ld].Valid = %ld\n", Isc, i,
                       SC[Isc].AC.FSS[i].Valid);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.FSS[%ld].SunAng = %18.12le %18.12le\n",
                       Isc, i, SC[Isc].AC.FSS[i].SunAng[0],
                       SC[Isc].AC.FSS[i].SunAng[1]);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }
            }

            for (i = 0; i < SC[Isc].AC.Nst; i++) {
               sprintf(line, "SC[%ld].AC.ST[%ld].Valid = %ld\n", Isc, i,
                       SC[Isc].AC.ST[i].Valid);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line,
                       "SC[%ld].AC.ST[%ld].qn = %18.12le %18.12le %18.12le "
                       "%18.12le\n",
                       Isc, i, SC[Isc].AC.ST[i].qn.q[0],
                       SC[Isc].AC.ST[i].qn.q[1], SC[Isc].AC.ST[i].qn.q[2],
                       SC[Isc].AC.ST[i].qn.q[3]);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }
            }

            for (i = 0; i < SC[Isc].AC.Ngps; i++) {
               sprintf(line, "SC[%ld].AC.GPS[%ld].Valid = %ld\n", Isc, i,
                       SC[Isc].AC.GPS[i].Valid);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.GPS[%ld].Rollover = %ld\n", Isc, i,
                       SC[Isc].AC.GPS[i].Rollover);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.GPS[%ld].Week = %ld\n", Isc, i,
                       SC[Isc].AC.GPS[i].Week);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.GPS[%ld].Sec = %18.12le\n", Isc, i,
                       SC[Isc].AC.GPS[i].Sec);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(
                   line,
                   "SC[%ld].AC.GPS[%ld].PosN = %18.12le %18.12le %18.12le\n",
                   Isc, i, SC[Isc].AC.GPS[i].PosN.v[0],
                   SC[Isc].AC.GPS[i].PosN.v[1], SC[Isc].AC.GPS[i].PosN.v[2]);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(
                   line,
                   "SC[%ld].AC.GPS[%ld].VelN = %18.12le %18.12le %18.12le\n",
                   Isc, i, SC[Isc].AC.GPS[i].VelN.v[0],
                   SC[Isc].AC.GPS[i].VelN.v[1], SC[Isc].AC.GPS[i].VelN.v[2]);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(
                   line,
                   "SC[%ld].AC.GPS[%ld].PosW = %18.12le %18.12le %18.12le\n",
                   Isc, i, SC[Isc].AC.GPS[i].PosW.v[0],
                   SC[Isc].AC.GPS[i].PosW.v[1], SC[Isc].AC.GPS[i].PosW.v[2]);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(
                   line,
                   "SC[%ld].AC.GPS[%ld].VelW = %18.12le %18.12le %18.12le\n",
                   Isc, i, SC[Isc].AC.GPS[i].VelW.v[0],
                   SC[Isc].AC.GPS[i].VelW.v[1], SC[Isc].AC.GPS[i].VelW.v[2]);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.GPS[%ld].Lng = %18.12le\n", Isc, i,
                       SC[Isc].AC.GPS[i].Lng);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.GPS[%ld].Lat = %18.12le\n", Isc, i,
                       SC[Isc].AC.GPS[i].Lat);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.GPS[%ld].Alt = %18.12le\n", Isc, i,
                       SC[Isc].AC.GPS[i].Alt);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.GPS[%ld].WgsLng = %18.12le\n", Isc, i,
                       SC[Isc].AC.GPS[i].WgsLng);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.GPS[%ld].WgsLat = %18.12le\n", Isc, i,
                       SC[Isc].AC.GPS[i].WgsLat);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.GPS[%ld].WgsAlt = %18.12le\n", Isc, i,
                       SC[Isc].AC.GPS[i].WgsAlt);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }
            }

            for (i = 0; i < SC[Isc].AC.Nacc; i++) {
               sprintf(line, "SC[%ld].AC.Accel[%ld].Acc = %18.12le\n", Isc, i,
                       SC[Isc].AC.Accel[i].Acc);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }
            }

            for (i = 0; i < SC[Isc].AC.Nwhl; i++) {
               sprintf(line, "SC[%ld].AC.Whl[%ld].H = %18.12le\n", Isc, i,
                       SC[Isc].AC.Whl[i].H);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }
            }

            for (i = 0; i < SC[Isc].Nb; i++) {
               sprintf(line, "SC[%ld].B[%ld].wn = %18.12le %18.12le %18.12le\n",
                       Isc, i, SC[Isc].B[i].wn.v[0], SC[Isc].B[i].wn.v[1],
                       SC[Isc].B[i].wn.v[2]);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(
                   line,
                   "SC[%ld].B[%ld].qn = %18.12le %18.12le %18.12le %18.12le\n",
                   Isc, i, SC[Isc].B[i].qn.q[0], SC[Isc].B[i].qn.q[1],
                   SC[Isc].B[i].qn.q[2], SC[Isc].B[i].qn.q[3]);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }
            }

            for (i = 0; i < SC[Isc].Ng; i++) {
               sprintf(line,
                       "SC[%ld].G[%ld].Pos = %18.12le %18.12le %18.12le\n", Isc,
                       i, SC[Isc].G[i].Pos.v[0], SC[Isc].G[i].Pos.v[1],
                       SC[Isc].G[i].Pos.v[2]);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line,
                       "SC[%ld].G[%ld].PosRate = %18.12le %18.12le %18.12le\n",
                       Isc, i, SC[Isc].G[i].PosRate.v[0],
                       SC[Isc].G[i].PosRate.v[1], SC[Isc].G[i].PosRate.v[2]);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line,
                       "SC[%ld].G[%ld].Ang = %18.12le %18.12le %18.12le\n", Isc,
                       i, SC[Isc].G[i].Ang.v[0], SC[Isc].G[i].Ang.v[1],
                       SC[Isc].G[i].Ang.v[2]);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line,
                       "SC[%ld].G[%ld].AngRate = %18.12le %18.12le %18.12le\n",
                       Isc, i, SC[Isc].G[i].AngRate.v[0],
                       SC[Isc].G[i].AngRate.v[1], SC[Isc].G[i].AngRate.v[2]);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }
            }

            sprintf(line, "SC[%ld].GN.Pos = %18.12le %18.12le %18.12le\n", Isc,
                    SC[Isc].GN.Pos.v[0], SC[Isc].GN.Pos.v[1],
                    SC[Isc].GN.Pos.v[2]);
            if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
               fprintf(StateFile, "%s", line);
               if (EchoEnabled)
                  printf("%s", line);
            }

            sprintf(line, "SC[%ld].GN.PosRate = %18.12le %18.12le %18.12le\n",
                    Isc, SC[Isc].GN.PosRate.v[0], SC[Isc].GN.PosRate.v[1],
                    SC[Isc].GN.PosRate.v[2]);
            if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
               fprintf(StateFile, "%s", line);
               if (EchoEnabled)
                  printf("%s", line);
            }

            sprintf(line, "SC[%ld].GN.Ang = %18.12le %18.12le %18.12le\n", Isc,
                    SC[Isc].GN.Ang.v[0], SC[Isc].GN.Ang.v[1],
                    SC[Isc].GN.Ang.v[2]);
            if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
               fprintf(StateFile, "%s", line);
               if (EchoEnabled)
                  printf("%s", line);
            }

            sprintf(line, "SC[%ld].GN.AngRate = %18.12le %18.12le %18.12le\n",
                    Isc, SC[Isc].GN.AngRate.v[0], SC[Isc].GN.AngRate.v[1],
                    SC[Isc].GN.AngRate.v[2]);
            if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
               fprintf(StateFile, "%s", line);
               if (EchoEnabled)
                  printf("%s", line);
            }

            for (i = 0; i < SC[Isc].Nw; i++) {
               sprintf(line, "SC[%ld].Whl[%ld].H = %18.12le\n", Isc, i,
                       SC[Isc].Whl[i].H);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }
            }

            for (i = 0; i < SC[Isc].Ngyro; i++) {
               sprintf(line, "SC[%ld].Gyro[%ld].TrueRate = %18.12le\n", Isc, i,
                       SC[Isc].Gyro[i].TrueRate);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }
            }
         }
      }

      for (Iw = 1; Iw < NWORLD; Iw++) {
         if (World[Iw].Exists) {
            sprintf(line, "World[%ld].PosH = %18.12le %18.12le %18.12le\n", Iw,
                    World[Iw].PosH.v[0], World[Iw].PosH.v[1],
                    World[Iw].PosH.v[2]);
            if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
               fprintf(StateFile, "%s", line);
               if (EchoEnabled)
                  printf("%s", line);
            }

            sprintf(line, "World[%ld].eph.PosN = %18.12le %18.12le %18.12le\n",
                    Iw, World[Iw].eph.PosN.v[0], World[Iw].eph.PosN.v[1],
                    World[Iw].eph.PosN.v[2]);
            if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
               fprintf(StateFile, "%s", line);
               if (EchoEnabled)
                  printf("%s", line);
            }

            sprintf(line, "World[%ld].eph.VelN = %18.12le %18.12le %18.12le\n",
                    Iw, World[Iw].eph.VelN.v[0], World[Iw].eph.VelN.v[1],
                    World[Iw].eph.VelN.v[2]);
            if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
               fprintf(StateFile, "%s", line);
               if (EchoEnabled)
                  printf("%s", line);
            }
         }
      }

      for (Iorb = 0; Iorb < Norb; Iorb++) {
         if (Orb[Iorb].Exists) {
            sprintf(line, "Orb[%ld].PosN = %18.12le %18.12le %18.12le\n", Iorb,
                    Orb[Iorb].PosN.v[0], Orb[Iorb].PosN.v[1],
                    Orb[Iorb].PosN.v[2]);
            if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
               fprintf(StateFile, "%s", line);
               if (EchoEnabled)
                  printf("%s", line);
            }

            sprintf(line, "Orb[%ld].VelN = %18.12le %18.12le %18.12le\n", Iorb,
                    Orb[Iorb].VelN.v[0], Orb[Iorb].VelN.v[1],
                    Orb[Iorb].VelN.v[2]);
            if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
               fprintf(StateFile, "%s", line);
               if (EchoEnabled)
                  printf("%s", line);
            }
         }
      }

      for (Isc = 0; Isc < Nsc; Isc++) {
         if (SC[Isc].Exists) {
            if (SC[Isc].AC.ParmLoadEnabled) {
               sprintf(line, "SC[%ld].AC.ID = %ld\n", Isc, SC[Isc].AC.ID);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.EchoEnabled = %ld\n", Isc,
                       SC[Isc].AC.EchoEnabled);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.Nb = %ld\n", Isc, SC[Isc].AC.Nb);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.Ng = %ld\n", Isc, SC[Isc].AC.Ng);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.Nwhl = %ld\n", Isc, SC[Isc].AC.Nwhl);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.Nmtb = %ld\n", Isc, SC[Isc].AC.Nmtb);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.Nthr = %ld\n", Isc, SC[Isc].AC.Nthr);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.Ncmg = %ld\n", Isc, SC[Isc].AC.Ncmg);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.Ngyro = %ld\n", Isc, SC[Isc].AC.Ngyro);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.Nmag = %ld\n", Isc, SC[Isc].AC.Nmag);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.Ncss = %ld\n", Isc, SC[Isc].AC.Ncss);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.Nfss = %ld\n", Isc, SC[Isc].AC.Nfss);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.Nst = %ld\n", Isc, SC[Isc].AC.Nst);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.Ngps = %ld\n", Isc, SC[Isc].AC.Ngps);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.Nacc = %ld\n", Isc, SC[Isc].AC.Nacc);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.Pi = %18.12le\n", Isc, SC[Isc].AC.Pi);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.TwoPi = %18.12le\n", Isc,
                       SC[Isc].AC.TwoPi);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.DT = %18.12le\n", Isc, SC[Isc].AC.DT);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.mass = %18.12le\n", Isc,
                       SC[Isc].AC.mass);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.cm = %18.12le %18.12le %18.12le\n",
                       Isc, SC[Isc].AC.cm.v[0], SC[Isc].AC.cm.v[1],
                       SC[Isc].AC.cm.v[2]);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line,
                       "SC[%ld].AC.MOI = %18.12le %18.12le %18.12le %18.12le "
                       "%18.12le %18.12le %18.12le %18.12le %18.12le\n",
                       Isc, SC[Isc].AC.MOI.mat[0][0], SC[Isc].AC.MOI.mat[0][1],
                       SC[Isc].AC.MOI.mat[0][2], SC[Isc].AC.MOI.mat[1][0],
                       SC[Isc].AC.MOI.mat[1][1], SC[Isc].AC.MOI.mat[1][2],
                       SC[Isc].AC.MOI.mat[2][0], SC[Isc].AC.MOI.mat[2][1],
                       SC[Isc].AC.MOI.mat[2][2]);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               for (i = 0; i < SC[Isc].AC.Nb; i++) {
                  sprintf(line, "SC[%ld].AC.B[%ld].mass = %18.12le\n", Isc, i,
                          SC[Isc].AC.B[i].mass);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }

                  sprintf(line,
                          "SC[%ld].AC.B[%ld].cm = %18.12le %18.12le %18.12le\n",
                          Isc, i, SC[Isc].AC.B[i].cm.v[0],
                          SC[Isc].AC.B[i].cm.v[1], SC[Isc].AC.B[i].cm.v[2]);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }

                  sprintf(
                      line,
                      "SC[%ld].AC.B[%ld].MOI = %18.12le %18.12le %18.12le "
                      "%18.12le %18.12le %18.12le %18.12le %18.12le %18.12le\n",
                      Isc, i, SC[Isc].AC.B[i].MOI.mat[0][0],
                      SC[Isc].AC.B[i].MOI.mat[0][1],
                      SC[Isc].AC.B[i].MOI.mat[0][2],
                      SC[Isc].AC.B[i].MOI.mat[1][0],
                      SC[Isc].AC.B[i].MOI.mat[1][1],
                      SC[Isc].AC.B[i].MOI.mat[1][2],
                      SC[Isc].AC.B[i].MOI.mat[2][0],
                      SC[Isc].AC.B[i].MOI.mat[2][1],
                      SC[Isc].AC.B[i].MOI.mat[2][2]);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }
               }

               for (i = 0; i < SC[Isc].AC.Ng; i++) {
                  sprintf(line, "SC[%ld].AC.G[%ld].IsSpherical = %ld\n", Isc, i,
                          SC[Isc].AC.G[i].IsSpherical);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }

                  sprintf(line, "SC[%ld].AC.G[%ld].RotDOF = %ld\n", Isc, i,
                          SC[Isc].AC.G[i].RotDOF);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }

                  sprintf(line, "SC[%ld].AC.G[%ld].TrnDOF = %ld\n", Isc, i,
                          SC[Isc].AC.G[i].TrnDOF);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }

                  sprintf(line, "SC[%ld].AC.G[%ld].RotSeq = %ld\n", Isc, i,
                          SC[Isc].AC.G[i].RotSeq);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }

                  sprintf(line, "SC[%ld].AC.G[%ld].TrnSeq = %ld\n", Isc, i,
                          SC[Isc].AC.G[i].TrnSeq);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }

                  sprintf(
                      line,
                      "SC[%ld].AC.G[%ld].CGiBi = %18.12le %18.12le %18.12le "
                      "%18.12le %18.12le %18.12le %18.12le %18.12le %18.12le\n",
                      Isc, i, SC[Isc].AC.G[i].CGiBi.mat[0][0],
                      SC[Isc].AC.G[i].CGiBi.mat[0][1],
                      SC[Isc].AC.G[i].CGiBi.mat[0][2],
                      SC[Isc].AC.G[i].CGiBi.mat[1][0],
                      SC[Isc].AC.G[i].CGiBi.mat[1][1],
                      SC[Isc].AC.G[i].CGiBi.mat[1][2],
                      SC[Isc].AC.G[i].CGiBi.mat[2][0],
                      SC[Isc].AC.G[i].CGiBi.mat[2][1],
                      SC[Isc].AC.G[i].CGiBi.mat[2][2]);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }

                  sprintf(
                      line,
                      "SC[%ld].AC.G[%ld].CBoGo = %18.12le %18.12le %18.12le "
                      "%18.12le %18.12le %18.12le %18.12le %18.12le %18.12le\n",
                      Isc, i, SC[Isc].AC.G[i].CBoGo.mat[0][0],
                      SC[Isc].AC.G[i].CBoGo.mat[0][1],
                      SC[Isc].AC.G[i].CBoGo.mat[0][2],
                      SC[Isc].AC.G[i].CBoGo.mat[1][0],
                      SC[Isc].AC.G[i].CBoGo.mat[1][1],
                      SC[Isc].AC.G[i].CBoGo.mat[1][2],
                      SC[Isc].AC.G[i].CBoGo.mat[2][0],
                      SC[Isc].AC.G[i].CBoGo.mat[2][1],
                      SC[Isc].AC.G[i].CBoGo.mat[2][2]);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }

                  sprintf(line,
                          "SC[%ld].AC.G[%ld].AngGain = %18.12le %18.12le "
                          "%18.12le\n",
                          Isc, i, SC[Isc].AC.G[i].AngGain.v[0],
                          SC[Isc].AC.G[i].AngGain.v[1],
                          SC[Isc].AC.G[i].AngGain.v[2]);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }

                  sprintf(line,
                          "SC[%ld].AC.G[%ld].AngRateGain = %18.12le %18.12le "
                          "%18.12le\n",
                          Isc, i, SC[Isc].AC.G[i].AngRateGain.v[0],
                          SC[Isc].AC.G[i].AngRateGain.v[1],
                          SC[Isc].AC.G[i].AngRateGain.v[2]);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }

                  sprintf(line,
                          "SC[%ld].AC.G[%ld].PosGain = %18.12le %18.12le "
                          "%18.12le\n",
                          Isc, i, SC[Isc].AC.G[i].PosGain.v[0],
                          SC[Isc].AC.G[i].PosGain.v[1],
                          SC[Isc].AC.G[i].PosGain.v[2]);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }

                  sprintf(line,
                          "SC[%ld].AC.G[%ld].PosRateGain = %18.12le %18.12le "
                          "%18.12le\n",
                          Isc, i, SC[Isc].AC.G[i].PosRateGain.v[0],
                          SC[Isc].AC.G[i].PosRateGain.v[1],
                          SC[Isc].AC.G[i].PosRateGain.v[2]);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }

                  sprintf(line,
                          "SC[%ld].AC.G[%ld].MaxAngRate = %18.12le %18.12le "
                          "%18.12le\n",
                          Isc, i, SC[Isc].AC.G[i].MaxAngRate.v[0],
                          SC[Isc].AC.G[i].MaxAngRate.v[1],
                          SC[Isc].AC.G[i].MaxAngRate.v[2]);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }

                  sprintf(line,
                          "SC[%ld].AC.G[%ld].MaxPosRate = %18.12le %18.12le "
                          "%18.12le\n",
                          Isc, i, SC[Isc].AC.G[i].MaxPosRate.v[0],
                          SC[Isc].AC.G[i].MaxPosRate.v[1],
                          SC[Isc].AC.G[i].MaxPosRate.v[2]);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }

                  sprintf(
                      line,
                      "SC[%ld].AC.G[%ld].MaxTrq = %18.12le %18.12le %18.12le\n",
                      Isc, i, SC[Isc].AC.G[i].MaxTrq.v[0],
                      SC[Isc].AC.G[i].MaxTrq.v[1], SC[Isc].AC.G[i].MaxTrq.v[2]);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }

                  sprintf(
                      line,
                      "SC[%ld].AC.G[%ld].MaxFrc = %18.12le %18.12le %18.12le\n",
                      Isc, i, SC[Isc].AC.G[i].MaxFrc.v[0],
                      SC[Isc].AC.G[i].MaxFrc.v[1], SC[Isc].AC.G[i].MaxFrc.v[2]);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }
               }

               for (i = 0; i < SC[Isc].AC.Ngyro; i++) {
                  sprintf(line,
                          "SC[%ld].AC.Gyro[%ld].Axis = %18.12le %18.12le "
                          "%18.12le\n",
                          Isc, i, SC[Isc].AC.Gyro[i].Axis.v[0],
                          SC[Isc].AC.Gyro[i].Axis.v[1],
                          SC[Isc].AC.Gyro[i].Axis.v[2]);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }
               }

               for (i = 0; i < SC[Isc].AC.Nmag; i++) {
                  sprintf(
                      line,
                      "SC[%ld].AC.MAG[%ld].Axis = %18.12le %18.12le %18.12le\n",
                      Isc, i, SC[Isc].AC.MAG[i].Axis.v[0],
                      SC[Isc].AC.MAG[i].Axis.v[1], SC[Isc].AC.MAG[i].Axis.v[2]);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }
               }

               for (i = 0; i < SC[Isc].AC.Ncss; i++) {
                  sprintf(line, "SC[%ld].AC.CSS[%ld].Body = %ld\n", Isc, i,
                          SC[Isc].AC.CSS[i].Body);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }

                  sprintf(
                      line,
                      "SC[%ld].AC.CSS[%ld].Axis = %18.12le %18.12le %18.12le\n",
                      Isc, i, SC[Isc].AC.CSS[i].Axis.v[0],
                      SC[Isc].AC.CSS[i].Axis.v[1], SC[Isc].AC.CSS[i].Axis.v[2]);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }

                  sprintf(line, "SC[%ld].AC.CSS[%ld].Scale = %18.12le\n", Isc,
                          i, SC[Isc].AC.CSS[i].Scale);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }
               }

               for (i = 0; i < SC[Isc].AC.Nfss; i++) {
                  sprintf(line,
                          "SC[%ld].AC.FSS[%ld].qb = %18.12le %18.12le %18.12le "
                          "%18.12le\n",
                          Isc, i, SC[Isc].AC.FSS[i].qb.q[0],
                          SC[Isc].AC.FSS[i].qb.q[1], SC[Isc].AC.FSS[i].qb.q[2],
                          SC[Isc].AC.FSS[i].qb.q[3]);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }

                  sprintf(
                      line,
                      "SC[%ld].AC.FSS[%ld].CB = %18.12le %18.12le %18.12le "
                      "%18.12le %18.12le %18.12le %18.12le %18.12le %18.12le\n",
                      Isc, i, SC[Isc].AC.FSS[i].CB.mat[0][0],
                      SC[Isc].AC.FSS[i].CB.mat[0][1],
                      SC[Isc].AC.FSS[i].CB.mat[0][2],
                      SC[Isc].AC.FSS[i].CB.mat[1][0],
                      SC[Isc].AC.FSS[i].CB.mat[1][1],
                      SC[Isc].AC.FSS[i].CB.mat[1][2],
                      SC[Isc].AC.FSS[i].CB.mat[2][0],
                      SC[Isc].AC.FSS[i].CB.mat[2][1],
                      SC[Isc].AC.FSS[i].CB.mat[2][2]);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }
               }

               for (i = 0; i < SC[Isc].AC.Nst; i++) {
                  sprintf(line,
                          "SC[%ld].AC.ST[%ld].qb = %18.12le %18.12le %18.12le "
                          "%18.12le\n",
                          Isc, i, SC[Isc].AC.ST[i].qb.q[0],
                          SC[Isc].AC.ST[i].qb.q[1], SC[Isc].AC.ST[i].qb.q[2],
                          SC[Isc].AC.ST[i].qb.q[3]);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }

                  sprintf(
                      line,
                      "SC[%ld].AC.ST[%ld].CB = %18.12le %18.12le %18.12le "
                      "%18.12le %18.12le %18.12le %18.12le %18.12le %18.12le\n",
                      Isc, i, SC[Isc].AC.ST[i].CB.mat[0][0],
                      SC[Isc].AC.ST[i].CB.mat[0][1],
                      SC[Isc].AC.ST[i].CB.mat[0][2],
                      SC[Isc].AC.ST[i].CB.mat[1][0],
                      SC[Isc].AC.ST[i].CB.mat[1][1],
                      SC[Isc].AC.ST[i].CB.mat[1][2],
                      SC[Isc].AC.ST[i].CB.mat[2][0],
                      SC[Isc].AC.ST[i].CB.mat[2][1],
                      SC[Isc].AC.ST[i].CB.mat[2][2]);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }
               }

               for (i = 0; i < SC[Isc].AC.Nacc; i++) {
                  sprintf(line,
                          "SC[%ld].AC.Accel[%ld].PosB = %18.12le %18.12le "
                          "%18.12le\n",
                          Isc, i, SC[Isc].AC.Accel[i].PosB.v[0],
                          SC[Isc].AC.Accel[i].PosB.v[1],
                          SC[Isc].AC.Accel[i].PosB.v[2]);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }

                  sprintf(line,
                          "SC[%ld].AC.Accel[%ld].Axis = %18.12le %18.12le "
                          "%18.12le\n",
                          Isc, i, SC[Isc].AC.Accel[i].Axis.v[0],
                          SC[Isc].AC.Accel[i].Axis.v[1],
                          SC[Isc].AC.Accel[i].Axis.v[2]);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }
               }

               for (i = 0; i < SC[Isc].AC.Nwhl; i++) {
                  sprintf(line, "SC[%ld].AC.Whl[%ld].Body = %ld\n", Isc, i,
                          SC[Isc].AC.Whl[i].Body);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }

                  sprintf(
                      line,
                      "SC[%ld].AC.Whl[%ld].Axis = %18.12le %18.12le %18.12le\n",
                      Isc, i, SC[Isc].AC.Whl[i].Axis.v[0],
                      SC[Isc].AC.Whl[i].Axis.v[1], SC[Isc].AC.Whl[i].Axis.v[2]);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }

                  sprintf(line,
                          "SC[%ld].AC.Whl[%ld].DistVec = %18.12le %18.12le "
                          "%18.12le\n",
                          Isc, i, SC[Isc].AC.Whl[i].DistVec.v[0],
                          SC[Isc].AC.Whl[i].DistVec.v[1],
                          SC[Isc].AC.Whl[i].DistVec.v[2]);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }

                  sprintf(line, "SC[%ld].AC.Whl[%ld].J = %18.12le\n", Isc, i,
                          SC[Isc].AC.Whl[i].J);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }

                  sprintf(line, "SC[%ld].AC.Whl[%ld].Tmax = %18.12le\n", Isc, i,
                          SC[Isc].AC.Whl[i].Tmax);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }

                  sprintf(line, "SC[%ld].AC.Whl[%ld].Hmax = %18.12le\n", Isc, i,
                          SC[Isc].AC.Whl[i].Hmax);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }
               }

               for (i = 0; i < SC[Isc].AC.Nmtb; i++) {
                  sprintf(
                      line,
                      "SC[%ld].AC.MTB[%ld].Axis = %18.12le %18.12le %18.12le\n",
                      Isc, i, SC[Isc].AC.MTB[i].Axis.v[0],
                      SC[Isc].AC.MTB[i].Axis.v[1], SC[Isc].AC.MTB[i].Axis.v[2]);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }

                  sprintf(line,
                          "SC[%ld].AC.MTB[%ld].DistVec = %18.12le %18.12le "
                          "%18.12le\n",
                          Isc, i, SC[Isc].AC.MTB[i].DistVec.v[0],
                          SC[Isc].AC.MTB[i].DistVec.v[1],
                          SC[Isc].AC.MTB[i].DistVec.v[2]);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }

                  sprintf(line, "SC[%ld].AC.MTB[%ld].Mmax = %18.12le\n", Isc, i,
                          SC[Isc].AC.MTB[i].Mmax);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }
               }

               for (i = 0; i < SC[Isc].AC.Nthr; i++) {
                  sprintf(line, "SC[%ld].AC.Thr[%ld].Body = %ld\n", Isc, i,
                          SC[Isc].AC.Thr[i].Body);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }

                  sprintf(
                      line,
                      "SC[%ld].AC.Thr[%ld].PosB = %18.12le %18.12le %18.12le\n",
                      Isc, i, SC[Isc].AC.Thr[i].PosB.v[0],
                      SC[Isc].AC.Thr[i].PosB.v[1], SC[Isc].AC.Thr[i].PosB.v[2]);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }

                  sprintf(
                      line,
                      "SC[%ld].AC.Thr[%ld].Axis = %18.12le %18.12le %18.12le\n",
                      Isc, i, SC[Isc].AC.Thr[i].Axis.v[0],
                      SC[Isc].AC.Thr[i].Axis.v[1], SC[Isc].AC.Thr[i].Axis.v[2]);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }

                  sprintf(
                      line,
                      "SC[%ld].AC.Thr[%ld].rxA = %18.12le %18.12le %18.12le\n",
                      Isc, i, SC[Isc].AC.Thr[i].rxA.v[0],
                      SC[Isc].AC.Thr[i].rxA.v[1], SC[Isc].AC.Thr[i].rxA.v[2]);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }

                  sprintf(line, "SC[%ld].AC.Thr[%ld].Fmax = %18.12le\n", Isc, i,
                          SC[Isc].AC.Thr[i].Fmax);
                  if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                     fprintf(StateFile, "%s", line);
                     if (EchoEnabled)
                        printf("%s", line);
                  }
               }

               sprintf(line, "SC[%ld].AC.PrototypeCtrl.wc = %18.12le\n", Isc,
                       SC[Isc].AC.PrototypeCtrl.wc);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.PrototypeCtrl.amax = %18.12le\n", Isc,
                       SC[Isc].AC.PrototypeCtrl.amax);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.PrototypeCtrl.vmax = %18.12le\n", Isc,
                       SC[Isc].AC.PrototypeCtrl.vmax);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.PrototypeCtrl.Kprec = %18.12le\n", Isc,
                       SC[Isc].AC.PrototypeCtrl.Kprec);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.PrototypeCtrl.Knute = %18.12le\n", Isc,
                       SC[Isc].AC.PrototypeCtrl.Knute);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line,
                       "SC[%ld].AC.AdHocCtrl.Kr = %18.12le %18.12le %18.12le\n",
                       Isc, SC[Isc].AC.AdHocCtrl.Kr.v[0],
                       SC[Isc].AC.AdHocCtrl.Kr.v[1],
                       SC[Isc].AC.AdHocCtrl.Kr.v[2]);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line,
                       "SC[%ld].AC.AdHocCtrl.Kp = %18.12le %18.12le %18.12le\n",
                       Isc, SC[Isc].AC.AdHocCtrl.Kp.v[0],
                       SC[Isc].AC.AdHocCtrl.Kp.v[1],
                       SC[Isc].AC.AdHocCtrl.Kp.v[2]);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.SpinnerCtrl.Ispin = %18.12le\n", Isc,
                       SC[Isc].AC.SpinnerCtrl.Ispin);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.SpinnerCtrl.Itrans = %18.12le\n", Isc,
                       SC[Isc].AC.SpinnerCtrl.Itrans);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.SpinnerCtrl.SpinRate = %18.12le\n",
                       Isc, SC[Isc].AC.SpinnerCtrl.SpinRate);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.SpinnerCtrl.Knute = %18.12le\n", Isc,
                       SC[Isc].AC.SpinnerCtrl.Knute);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.SpinnerCtrl.Kprec = %18.12le\n", Isc,
                       SC[Isc].AC.SpinnerCtrl.Kprec);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(
                   line,
                   "SC[%ld].AC.ThreeAxisCtrl.Kr = %18.12le %18.12le %18.12le\n",
                   Isc, SC[Isc].AC.ThreeAxisCtrl.Kr.v[0],
                   SC[Isc].AC.ThreeAxisCtrl.Kr.v[1],
                   SC[Isc].AC.ThreeAxisCtrl.Kr.v[2]);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(
                   line,
                   "SC[%ld].AC.ThreeAxisCtrl.Kp = %18.12le %18.12le %18.12le\n",
                   Isc, SC[Isc].AC.ThreeAxisCtrl.Kp.v[0],
                   SC[Isc].AC.ThreeAxisCtrl.Kp.v[1],
                   SC[Isc].AC.ThreeAxisCtrl.Kp.v[2]);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.ThreeAxisCtrl.Kunl = %18.12le\n", Isc,
                       SC[Isc].AC.ThreeAxisCtrl.Kunl);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line,
                       "SC[%ld].AC.IssCtrl.Kr = %18.12le %18.12le %18.12le\n",
                       Isc, SC[Isc].AC.IssCtrl.Kr.v[0],
                       SC[Isc].AC.IssCtrl.Kr.v[1], SC[Isc].AC.IssCtrl.Kr.v[2]);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line,
                       "SC[%ld].AC.IssCtrl.Kp = %18.12le %18.12le %18.12le\n",
                       Isc, SC[Isc].AC.IssCtrl.Kp.v[0],
                       SC[Isc].AC.IssCtrl.Kp.v[1], SC[Isc].AC.IssCtrl.Kp.v[2]);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.IssCtrl.Tmax = %18.12le\n", Isc,
                       SC[Isc].AC.IssCtrl.Tmax);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line,
                       "SC[%ld].AC.CmgCtrl.Kr = %18.12le %18.12le %18.12le\n",
                       Isc, SC[Isc].AC.CmgCtrl.Kr.v[0],
                       SC[Isc].AC.CmgCtrl.Kr.v[1], SC[Isc].AC.CmgCtrl.Kr.v[2]);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line,
                       "SC[%ld].AC.CmgCtrl.Kp = %18.12le %18.12le %18.12le\n",
                       Isc, SC[Isc].AC.CmgCtrl.Kp.v[0],
                       SC[Isc].AC.CmgCtrl.Kp.v[1], SC[Isc].AC.CmgCtrl.Kp.v[2]);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line,
                       "SC[%ld].AC.ThrCtrl.Kw = %18.12le %18.12le %18.12le\n",
                       Isc, SC[Isc].AC.ThrCtrl.Kw.v[0],
                       SC[Isc].AC.ThrCtrl.Kw.v[1], SC[Isc].AC.ThrCtrl.Kw.v[2]);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line,
                       "SC[%ld].AC.ThrCtrl.Kth = %18.12le %18.12le %18.12le\n",
                       Isc, SC[Isc].AC.ThrCtrl.Kth.v[0],
                       SC[Isc].AC.ThrCtrl.Kth.v[1],
                       SC[Isc].AC.ThrCtrl.Kth.v[2]);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.ThrCtrl.Kv = %18.12le\n", Isc,
                       SC[Isc].AC.ThrCtrl.Kv);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.ThrCtrl.Kp = %18.12le\n", Isc,
                       SC[Isc].AC.ThrCtrl.Kp);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line,
                       "SC[%ld].AC.CfsCtrl.Kr = %18.12le %18.12le %18.12le\n",
                       Isc, SC[Isc].AC.CfsCtrl.Kr.v[0],
                       SC[Isc].AC.CfsCtrl.Kr.v[1], SC[Isc].AC.CfsCtrl.Kr.v[2]);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line,
                       "SC[%ld].AC.CfsCtrl.Kp = %18.12le %18.12le %18.12le\n",
                       Isc, SC[Isc].AC.CfsCtrl.Kp.v[0],
                       SC[Isc].AC.CfsCtrl.Kp.v[1], SC[Isc].AC.CfsCtrl.Kp.v[2]);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(line, "SC[%ld].AC.CfsCtrl.Kunl = %18.12le\n", Isc,
                       SC[Isc].AC.CfsCtrl.Kunl);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(
                   line,
                   "SC[%ld].AC.ThrSteerCtrl.Kr = %18.12le %18.12le %18.12le\n",
                   Isc, SC[Isc].AC.ThrSteerCtrl.Kr.v[0],
                   SC[Isc].AC.ThrSteerCtrl.Kr.v[1],
                   SC[Isc].AC.ThrSteerCtrl.Kr.v[2]);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }

               sprintf(
                   line,
                   "SC[%ld].AC.ThrSteerCtrl.Kp = %18.12le %18.12le %18.12le\n",
                   Isc, SC[Isc].AC.ThrSteerCtrl.Kp.v[0],
                   SC[Isc].AC.ThrSteerCtrl.Kp.v[1],
                   SC[Isc].AC.ThrSteerCtrl.Kp.v[2]);
               if (!strncmp(line, Prefix[Ipfx], PfxLen)) {
                  fprintf(StateFile, "%s", line);
                  if (EchoEnabled)
                     printf("%s", line);
               }
            }
         }
      }
   }

   sprintf(line, "[EOF]\n\n");
   if (EchoEnabled)
      printf("%s", line);

   fprintf(StateFile, "%s", line);
}
