name: C/C++ CI

# run only on pushes or pull requests to master
# this way you can develop on and push to separate branches without
# using up runner minutes
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  setup-ubuntu: &setup-ubuntu |
    sudo apt-get update
    sudo apt-get -y install pkg-config libfyaml-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev libcriterion-dev
  setup-macos: &setup-macos |
    brew update
    brew install pkgconfig libfyaml freeglut mesa-glu criterion
  setup-ubuntu-glfw: &setup-ubuntu-glfw |
    sudo apt-get -y install libglfw3-dev
  setup-macos-glfw: &setup-macos-glfw |
    brew install glfw

jobs:
  test-build:
    # Ubuntu and MacOS build in various conditions
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: Ubuntu (x86-64)
            os: ubuntu-latest
            setup: *setup-ubuntu
            glfw-setup: *setup-ubuntu-glfw
          - name: macOS (AArch64)
            os: macos-latest
            setup: *setup-macos
            glfw-setup: *setup-macos-glfw
        compiler: [gcc, clang]
        glut: ["GLUT", "GLFW"]
        spice: ["ON", "OFF"]
        build: ["Release", "Debug"]
        exclude:
          - glut: "GLFW"
            spice: "ON"
          - glut: "GLFW"
            build: "debug"
          # gcc not normally present on mac, unless installed from e.g. homebrew
          - platform:
              os: "macos-latest"
            compiler: "gcc"

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Platform setup
        run: ${{ matrix.platform.setup }}

      - name: Checkout deepthought
        uses: actions/checkout@v6

      - name: get GLFW
        if: ${{ (matrix.glut == 'GLFW') }}
        run: ${{ matrix.platform.glfw-setup }}

      - name: get cspice
        if: ${{ matrix.spice == 'ON' }}
        run: ./download_spice.sh

      - name: set compiler
        run: export CC=$(which ${{ matrix.compiler }})

      - name: Cmake Configuration
        run: cmake --preset ${{ matrix.build }} -DSPICE=${{ matrix.spice }} -DGLUT_OR_GLFW=${{ matrix.glut }}
      
      - name: add homebrew to cmake path
        if: ${{ matrix.glut == 'GLFW' && contains(matrix.platform.os, 'macos') }}
        run: cmake -DCMAKE_PREFIX_PATH=$(brew --prefix) -S . -B build/${{ matrix.build }}

      - name: Build
        run: cmake --build --preset ${{ matrix.build }}-build --clean-first

      - name: Run Tests
        run: ctest --preset test-${{ matrix.build }}
