name: Clang Format Checker
on: [ push ]
jobs:
   clang-format-checking:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v5
         - name: Set up Homebrew
           uses: Homebrew/actions/setup-homebrew@main
         - name: Install/Update clang-format
           run: HOMEBREW_NO_AUTO_UPDATE=1 brew install clang-format
         - name: Update PATH
           run: echo 'export PATH="/home/linuxbrew/.linuxbrew/opt/clang-format/bin:$PATH"'
              >> /home/runner/.bash_profile
         - name: Check with Brew's clang-format
           run: clang-format --dry-run --Werror --style=file Source/*.c Include/*.h
              Kit/Source/*.c Kit/Include/*.h
         - name: Give clang-format version
           run: echo "Formatted with clang-format version $(clang-format --version)"
